web:
  url_epc: https://epc.lib.tuke.sk/PrehladPubl.aspx
  url_crepc_1: http://www.crepc.sk/portal?fn=SearchForm
  url_crepc_2: https://app.crepc.sk

# 9 - Rektorat # 2 - SJF

data:
  #faculty: rek
  #faculty_index: 9
  faculty: sjf
  faculty_index: 2
  remove: false  #clean old html_files and csv files